### ISSUE TITLE
Bot refusing to respond to commands

### ISSUE THREAD

**Issue by Longpiggy** [VelkanGk/vgk-discord-bot#1]
I would assume that it's to do with Discord's recent change in which all commands were transitioned to "slash" commands.
The bot is in my server and online, but no commands work. Are there any plans to update this at all?

Thanks

**Comment by VelkanGk** [comment]
Hi @posercorpse !
As a matter of fact it is, due to discord updates the prefix setting has change and since I run it locally from my pc I have missed this issue. But answering your question, yes, there are plans to update it in future.

I'm glad to hear someone is using it!
